### ISSUE TITLE
Counterparties

### ISSUE THREAD

**Issue by melsomino** [tonlabs/ton-q-server#158]
# Problem

As a developer I want to get all the account's counterparties (wallets that sent transactions to my wallet and vise versa) when my application starts so that I can show this list immediately and subscribe to updates in this list.

# Solution

Create collection with message summary between accounts.

## GraphQL

```graphql
query {
    counterparties(
        account: "0:123123123",
        first: 20,
        # does not include cursor record itself in the result
        after?:cursor 
    ) {
        counterparties {
            # Counterparty account address
            counterparty
            last_message_id
            last_message_value
            # Last message time
            last_message_at
            last_message_is_reversed
            # Cursor that can be used as an `after` parameter 
            # to query next page.
            # Important! Use cursor of the LAST element in the list
            cursor 
        }
    }
}

subscribe {
    counterparties(account: "0:123123123") {
        counterparties {
            counterparty
            last_message_id
            last_message_value
            last_message_at
            last_message_is_reversed
        }
    }
}

```

Attention! Unstable pagination: because of the results sorted by `last_message_at` the paginated fetch can skip and duplicate some entries. To avoid this problem client has to:

- Start the subscription before a query (or do it simultaneously) and update the data views with the received data upon an event triggered by the subscription, so that no data is skipped or duplicated.
- Merge (deduplicate and resort) fetched data with visible data

**Comment by elasticLove1** [comment]
@NoamDev Updated the problem description, now it sounds more general. Basically this is the case of Surf chats.

**Comment by NoamDev** [comment]
Oh, I see
Well, I don't think this should be part of graphql because surf chats arr currently just stored on firestore or another firebase service, they are not very decentralized currently nor really related to Free TON
Once TON DB is introduced and chats move to there it would make sense, but for now it would be best to use the apis of firebase for that (maybe Surf Devs can exapnd on how exactly).
