### ISSUE TITLE
q-server ignore Q_REQUESTS_SERVER 

### ISSUE THREAD

**Issue by SkySonR** [tonlabs/ton-q-server#159]
ENV Q_REQUESTS_SERVER does not change anything. Looks like kafka location was taken from ton-node. It brokes configuration when we have kafka in docker network and ton-node in the host.

**Comment by alex-novikov-1990** [comment]
Sorry for response delay. Is this still relevant?

q-server knows nothing about ton-node, it takes kafka location from the configuration with "command line params > config file (since 0.41.0) > envs > defaults" priorities.

**Comment by SkySonR** [comment]
Sorry, everything works. Issue can be closed
